/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/db": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Database Health */
        get: operations["database_health_health_db_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/points": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Points */
        get: operations["get_points_points_get"];
        put?: never;
        /** Create Point */
        post: operations["create_point_points_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * PointCreate
         * @description Request payload for creating a new geographic point.
         */
        PointCreate: {
            /**
             * Lat
             * @description Latitude coordinate in WGS84 spatial reference system
             */
            lat: number;
            /**
             * Lon
             * @description Longitude coordinate in WGS84 spatial reference system
             */
            lon: number;
        };
        /**
         * PointListItem
         * @description Response model for a point in list views.
         *
         *     Returned by GET /points. Contains minimal fields for efficient list display.
         */
        PointListItem: {
            /**
             * Id
             * @description Unique point identifier
             */
            id: number;
            /**
             * Lat
             * @description Latitude coordinate (WGS84)
             */
            lat: number;
            /**
             * Lon
             * @description Longitude coordinate (WGS84)
             */
            lon: number;
        };
        /**
         * PointResponse
         * @description Response model for a single point with full details.
         *
         *     Returned by POST /points after creating a new point.
         */
        PointResponse: {
            /**
             * Id
             * @description Unique point identifier
             */
            id: number;
            /**
             * Lat
             * @description Latitude coordinate (WGS84)
             */
            lat: number;
            /**
             * Lon
             * @description Longitude coordinate (WGS84)
             */
            lon: number;
            /**
             * Srid
             * @description Spatial Reference System Identifier (typically 4326 for WGS84)
             */
            srid: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    database_health_health_db_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    get_points_points_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PointListItem"][];
                };
            };
        };
    };
    create_point_points_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PointCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PointResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
