/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/live/vessels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Live Vessels */
        get: operations["get_live_vessels_live_vessels_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/db": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Database Health */
        get: operations["database_health_health_db_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/points": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Points */
        get: operations["get_points_points_get"];
        put?: never;
        /** Create Point */
        post: operations["create_point_points_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * LiveVesselMapItem
         * @description Temporary live map render contract, not a persisted vessel domain model.
         */
        LiveVesselMapItem: {
            /**
             * Id
             * @description Stable frontend marker identifier derived from the live source
             */
            id: string;
            /**
             * Lat
             * @description Latitude coordinate (WGS84)
             */
            lat: number;
            /**
             * Lon
             * @description Longitude coordinate (WGS84)
             */
            lon: number;
            /**
             * Timestamp
             * @description Source timestamp for this live position
             */
            timestamp?: string | null;
            /**
             * Lastseenat
             * @description UTC time this vessel snapshot was last refreshed
             */
            lastSeenAt?: string | null;
            /**
             * Freshness
             * @description Freshness state derived from lastSeenAt
             * @enum {string}
             */
            freshness?: "fresh" | "stale" | null;
            /**
             * Mmsi
             * @description Maritime Mobile Service Identity when available
             */
            mmsi?: number | null;
            /**
             * Label
             * @description Display label for the vessel marker
             */
            label?: string | null;
            /**
             * Course
             * @description Course over ground
             */
            course?: number | null;
            /**
             * Heading
             * @description True heading
             */
            heading?: number | null;
            /**
             * Speed
             * @description Speed over ground
             */
            speed?: number | null;
            /**
             * Destination
             * @description Reported destination when available
             */
            destination?: string | null;
        };
        /** LiveVesselsMetadata */
        LiveVesselsMetadata: {
            /**
             * Source
             * @description Configured AIS source for the live snapshot
             */
            source: string;
            /**
             * Fetchedat
             * @description API snapshot read completion time in UTC
             */
            fetchedAt: string;
            /**
             * Knowncount
             * @description Number of vessel IDs known in the live Redis snapshot
             */
            knownCount: number;
            /**
             * Returnedcount
             * @description Number of live vessel items returned
             */
            returnedCount: number;
            /**
             * Lastmessageat
             * @description Newest source message time in returned items
             */
            lastMessageAt?: string | null;
            /**
             * Oldestlastseenat
             * @description Oldest cache refresh time in returned items
             */
            oldestLastSeenAt?: string | null;
            /**
             * Sourcestatus
             * @description Latest live source status reported by the consumer
             */
            sourceStatus: {
                [key: string]: unknown;
            };
            /**
             * Boundingboxes
             * @description AIS source bounding boxes configured for the live snapshot
             */
            boundingBoxes: unknown[];
        };
        /** LiveVesselsResponse */
        LiveVesselsResponse: {
            /**
             * Items
             * @description Minimal live vessel items for map rendering
             */
            items: components["schemas"]["LiveVesselMapItem"][];
            /** @description Fetch metadata for poll freshness checks */
            metadata: components["schemas"]["LiveVesselsMetadata"];
        };
        /** PointCreate */
        PointCreate: {
            /**
             * Lat
             * @description Latitude coordinate in WGS84 spatial reference system
             */
            lat: number;
            /**
             * Lon
             * @description Longitude coordinate in WGS84 spatial reference system
             */
            lon: number;
        };
        /** PointListItem */
        PointListItem: {
            /**
             * Id
             * @description Unique point identifier
             */
            id: number;
            /**
             * Lat
             * @description Latitude coordinate (WGS84)
             */
            lat: number;
            /**
             * Lon
             * @description Longitude coordinate (WGS84)
             */
            lon: number;
        };
        /** PointResponse */
        PointResponse: {
            /**
             * Id
             * @description Unique point identifier
             */
            id: number;
            /**
             * Lat
             * @description Latitude coordinate (WGS84)
             */
            lat: number;
            /**
             * Lon
             * @description Longitude coordinate (WGS84)
             */
            lon: number;
            /**
             * Srid
             * @description Spatial Reference System Identifier (typically 4326 for WGS84)
             */
            srid: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    get_live_vessels_live_vessels_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LiveVesselsResponse"];
                };
            };
        };
    };
    database_health_health_db_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    get_points_points_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PointListItem"][];
                };
            };
        };
    };
    create_point_points_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PointCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PointResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
